//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
public class EnemyQueue
{
		public string pattern;
	public string enemy;
	public string path;
	public double time;


				public EnemyQueue (string p, string e, string pa, double t)
				{
			pattern = p;
			enemy = e;
			path = pa;
			time = t;
				}
		}

